version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: nwt_project
    environment:
      - MONGO_DATA_DIR=/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./db:/db
    ports:
      - 27017:27017
